### ISSUE TITLE
Actoins TODO

### ISSUE THREAD

**Issue by tsuyoshicho** [tsuyoshicho/actions#2]
ToDo

**Comment by tsuyoshicho** [comment]
- [x] Redpen finish.

**Comment by tsuyoshicho** [comment]
Check bumpup adaptation for All GitHub Acitons support repo.

- https://github.com/haya14busa/action-bumpr
- https://github.com/haya14busa/action-update-semver/blob/master/.github/workflows/release.yml

If do so, add badge like action-update-semver

- [x] [tsuyoshicho/action-textlint](https://github.com/tsuyoshicho/action-textlint)
- [x] [tsuyoshicho/action-redpen](https://github.com/tsuyoshicho/action-redpen)
- [x] [tsuyoshicho/action-vimhelp-html-generate](https://github.com/tsuyoshicho/action-vimhelp-html-generate)
- [x] [tsuyoshicho/action-vimlint](https://github.com/tsuyoshicho/action-vimlint)
- [x] [tsuyoshicho/action-vimhelp-tagname-check](https://github.com/tsuyoshicho/action-vimhelp-tagname-check)

**Comment by tsuyoshicho** [comment]
check reviewdog and other manual version up terget,

- https://github.com/haya14busa/action-depup

FIX
- [x] https://github.com/tsuyoshicho/vital.vim
- [x] https://github.com/tsuyoshicho/vital-codec
- [x] https://github.com/tsuyoshicho/action-vimlint
- [x] https://github.com/tsuyoshicho/action-redpen
- [x] https://github.com/tsuyoshicho/action-textlint

**Comment by tsuyoshicho** [comment]
Renovate

**Comment by tsuyoshicho** [comment]
## Update each action version

- https://github.com/EndBug/add-and-commit
- https://github.com/JamesIves/github-pages-deploy-action

and other

## commit create action check
- https://github.com/EndBug/add-and-commit
- https://github.com/peter-evans/create-pull-request need fix (why : use old set-env and error happen)

**Comment by tsuyoshicho** [comment]
# Docker image to packages?

## example for packaged action

- https://github.com/JamesIves/github-pages-deploy-action
  release and use package (but this is npm)

## related action

- https://github.com/docker/build-push-action
  - https://github.com/docker/login-action#github-container-registry
- https://github.com/reviewdog/action-setup

## usage sample

- [GitHub ActionsでDockerコンテナをGitHub Package RegistryやDocker Hubにpushした話 \- Qiita](https://qiita.com/fagai/items/3a29cc1f5c5da5e571c9)
- [GitHub Container Registry\(ghcr\.io\)にDockerイメージをpushする手順 \- Qiita](https://qiita.com/zembutsu/items/1effae6c39ceae3c3d0a)
- [GitHub ActionsでDockerコンテナをGitHub Package RegistryやDocker Hubにpushした話 \- Qiita](https://qiita.com/fagai/items/3a29cc1f5c5da5e571c9)

**Comment by tsuyoshicho** [comment]
https://github.com/haya14busa/action-cond
use pull-req check for all workflow...

**Comment by tsuyoshicho** [comment]
https://github.com/reviewdog/action-eslint/blob/master/action.yml

update option and args
